export const CLUSTERS = [
  {
    id: 'alpha',
    letter: 'α',
    subgraphIndex: '01',
    name: 'Cluster α: Offshore FinTech',
    zoneTag: 'PRIMARY COHESION ZONE',
    color: '#38bdf8',
    partitionId: 'COM-CLUST-ALPHA',
    stabilityIndex: '94.2%',
    correlation: 'HIGH (0.84)',
    size: 9,
    sizePct: 32,
    internalDensity: 0.78,
    externalDensity: 0.14,
    analysis:
      'The cluster exhibits exceptionally high internal cohesion (0.78 density) coupled with sparse boundary permeability (0.14 external bridging). This topology is characteristic of a tightly-knit, closed operational cell where coordination occurs primarily through internal bilateral conduits with isolated egress choke points to external counterparties.',
    members: [
      { rank: 1, name: 'Al-Miraj Forex Gateway', tag: 'GATEWAY', tagVariant: 'default', icon: 'gateway', score: 0.887 },
      { rank: 2, name: 'Valkyrie Holdings Ltd', tag: 'ENTITY', tagVariant: 'gold', icon: 'entity', score: 0.765 },
      { rank: 3, name: 'Apex Settlement Pool 4', tag: 'POOL', tagVariant: 'default', icon: 'pool', score: 0.72 },
      { rank: 4, name: 'Boreas Logistics BV', tag: 'SHELL', tagVariant: 'default', icon: 'shell', score: 0.689 },
      { rank: 5, name: 'Helios Transponder Relay', tag: 'COMM', tagVariant: 'default', icon: 'comm', score: 0.612 },
      { rank: 6, name: 'Victor Chen (Nominee)', tag: 'INDIVIDUAL', tagVariant: 'teal', icon: 'individual', score: 0.54 },
      { rank: 7, name: 'Nicosia Intermediary SpA', tag: 'FIDUCIARY', tagVariant: 'default', icon: 'fiduciary', score: 0.482 },
      { rank: 8, name: 'Levant Clearing Hub', tag: 'CLEARING', tagVariant: 'default', icon: 'clearing', score: 0.415 },
      { rank: 9, name: 'Sentinel Nominee Trust', tag: 'FIDUCIARY', tagVariant: 'default', icon: 'fiduciary', score: 0.362 },
    ],
  },
  {
    id: 'beta',
    letter: 'β',
    subgraphIndex: '02',
    name: 'Cluster β: Layered Shell Entities',
    zoneTag: 'DISTRIBUTED MESH ZONE',
    color: '#c084fc',
    partitionId: 'COM-CLUST-BETA',
    stabilityIndex: '88.6%',
    correlation: 'MEDIUM (0.61)',
    size: 12,
    sizePct: 43,
    internalDensity: 0.52,
    externalDensity: 0.31,
    analysis:
      'The cluster shows moderate internal cohesion (0.52 density) with elevated external bridging (0.31), indicating a distributed layering structure where multiple shell entities exchange value across cluster boundaries to obscure beneficial ownership.',
    members: [
      { rank: 1, name: 'Kestrel Escrow AG', tag: 'ESCROW', tagVariant: 'default', icon: 'pool', score: 0.814 },
      { rank: 2, name: 'Meridian Shelf Holdings', tag: 'SHELL', tagVariant: 'default', icon: 'shell', score: 0.741 },
      { rank: 3, name: 'Kestrel Capital Escrow', tag: 'ENTITY', tagVariant: 'gold', icon: 'entity', score: 0.703 },
      { rank: 4, name: 'Orinoco Nominee Services', tag: 'FIDUCIARY', tagVariant: 'default', icon: 'fiduciary', score: 0.658 },
      { rank: 5, name: 'Silverline Trading FZE', tag: 'SHELL', tagVariant: 'default', icon: 'shell', score: 0.601 },
      { rank: 6, name: 'Petra Consulting DMCC', tag: 'FIDUCIARY', tagVariant: 'default', icon: 'fiduciary', score: 0.549 },
      { rank: 7, name: 'Tomas Reyes (Director)', tag: 'INDIVIDUAL', tagVariant: 'teal', icon: 'individual', score: 0.487 },
      { rank: 8, name: 'Aurelia Clearing Ltd', tag: 'CLEARING', tagVariant: 'default', icon: 'clearing', score: 0.421 },
    ],
  },
  {
    id: 'gamma',
    letter: 'γ',
    subgraphIndex: '03',
    name: 'Cluster γ: Escrow & Settlement',
    zoneTag: 'SETTLEMENT HUB ZONE',
    color: '#fbbf24',
    partitionId: 'COM-CLUST-GAMMA',
    stabilityIndex: '91.0%',
    correlation: 'HIGH (0.77)',
    size: 11,
    sizePct: 39,
    internalDensity: 0.65,
    externalDensity: 0.19,
    analysis:
      'The cluster centers on escrow and settlement infrastructure with high internal cohesion (0.65) and modest external bridging (0.19), consistent with a hub-and-spoke settlement layer routing value between the other two clusters.',
    members: [
      { rank: 1, name: 'Apex Settlement Pool 4', tag: 'POOL', tagVariant: 'default', icon: 'pool', score: 0.72 },
      { rank: 2, name: 'CipherKey Relay Node 07', tag: 'GATEWAY', tagVariant: 'default', icon: 'gateway', score: 0.492 },
      { rank: 3, name: 'Levant Clearing Hub', tag: 'CLEARING', tagVariant: 'default', icon: 'clearing', score: 0.415 },
      { rank: 4, name: 'Mikhail Sarkis', tag: 'INDIVIDUAL', tagVariant: 'teal', icon: 'individual', score: 0.543 },
      { rank: 5, name: 'Maritime Prime Trust', tag: 'FIDUCIARY', tagVariant: 'default', icon: 'fiduciary', score: 0.641 },
      { rank: 6, name: 'Boreas Logistics BV', tag: 'SHELL', tagVariant: 'default', icon: 'shell', score: 0.598 },
      { rank: 7, name: 'Helios Transponder Relay', tag: 'COMM', tagVariant: 'default', icon: 'comm', score: 0.612 },
    ],
  },
]
